"""initial schema with all tables

Revision ID: f204de5617f8
Revises: 
Create Date: 2026-06-12 16:50:46.972340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f204de5617f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('lang_aliases', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('name', name=op.f('uq_entities_name'))
    )
    op.create_table('resolution_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('parent_company', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('mono_brand', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resolution_cache')),
    sa.UniqueConstraint('query_text', name=op.f('uq_resolution_cache_query_text'))
    )
    op.create_table('entity_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['entities.id'], name=op.f('fk_entity_links_child_id_entities')),
    sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], name=op.f('fk_entity_links_parent_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_links'))
    )
    op.create_table('entity_mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('matched_text', sa.String(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('intent', sa.String(length=30), nullable=True),
    sa.Column('intent_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_mentions_entity_id_entities')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_entity_mentions_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_mentions'))
    )
    op.create_index('idx_entity_mentions_entity', 'entity_mentions', ['entity_id', 'created_at'], unique=False)
    op.create_table('entity_metrics_hourly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('ts_hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('weighted_mentions', sa.Float(), nullable=True),
    sa.Column('sentiment_mean', sa.Float(), nullable=True),
    sa.Column('sentiment_std', sa.Float(), nullable=True),
    sa.Column('intent_purchase_share', sa.Float(), nullable=True),
    sa.Column('intent_churn_share', sa.Float(), nullable=True),
    sa.Column('scarcity_share', sa.Float(), nullable=True),
    sa.Column('unique_authors', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_metrics_hourly_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_metrics_hourly'))
    )
    op.create_index('idx_entity_metrics_hourly', 'entity_metrics_hourly', ['entity_id', 'ts_hour'], unique=False)
    op.create_table('entity_tickers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('mcap_usd', sa.Float(), nullable=True),
    sa.Column('revenue_share_est', sa.Float(), nullable=True),
    sa.Column('mono_brand', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_tickers_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_tickers'))
    )
    op.create_index('idx_entity_tickers_ticker', 'entity_tickers', ['ticker'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('tickers', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('signal_score', sa.Float(), nullable=True),
    sa.Column('gap_score', sa.Float(), nullable=True),
    sa.Column('demand_index', sa.Float(), nullable=True),
    sa.Column('awareness_index', sa.Float(), nullable=True),
    sa.Column('velocity_z', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('corroboration', sa.Integer(), nullable=True),
    sa.Column('intent_purchase_share', sa.Float(), nullable=True),
    sa.Column('materiality', sa.Float(), nullable=True),
    sa.Column('regions', sa.Text(), nullable=True),
    sa.Column('origin_platform', sa.String(length=30), nullable=True),
    sa.Column('novelty', sa.Boolean(), nullable=True),
    sa.Column('evidence_post_ids', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_signals_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_table('verdicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_verdicts_signal_id_signals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verdicts'))
    )
    op.add_column('posts', sa.Column('lang', sa.String(length=10), nullable=True))
    op.alter_column('posts', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('posts', 'post_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('posts', 'author',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('posts', 'region',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('posts', 'sentiment',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('posts', 'topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('posts_post_id_key'), 'posts', type_='unique')
    op.drop_index(op.f('idx_posts_timestamp'), table_name='posts')
    op.create_index('idx_posts_timestamp', 'posts', ['timestamp'], unique=False)
    op.create_index('idx_posts_lang', 'posts', ['lang'], unique=False)
    op.create_unique_constraint(op.f('uq_posts_post_id'), 'posts', ['post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_posts_post_id'), 'posts', type_='unique')
    op.drop_index('idx_posts_lang', table_name='posts')
    op.drop_index('idx_posts_timestamp', table_name='posts')
    op.create_index(op.f('idx_posts_timestamp'), 'posts', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_unique_constraint(op.f('posts_post_id_key'), 'posts', ['post_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('posts', 'topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('posts', 'sentiment',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('posts', 'region',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('posts', 'author',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('posts', 'post_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('posts', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('posts', 'lang')
    op.drop_table('verdicts')
    op.drop_table('signals')
    op.drop_index('idx_entity_tickers_ticker', table_name='entity_tickers')
    op.drop_table('entity_tickers')
    op.drop_index('idx_entity_metrics_hourly', table_name='entity_metrics_hourly')
    op.drop_table('entity_metrics_hourly')
    op.drop_index('idx_entity_mentions_entity', table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_table('entity_links')
    op.drop_table('resolution_cache')
    op.drop_table('entities')
    # ### end Alembic commands ###
